### ISSUE TITLE
If I want to train model with yolov5, How can I do it？

### ISSUE THREAD

**Issue by WangRongsheng** [fastestimator/fastestimator#1317]
Hello,
I want to try to use yolov5 in fastestimator to train model, what should my dataset look like?

such as：
```python
.
│
├─Annotations
│	1.xml
|       2.xml
|       3.xml
|       ...
└─JPEGImages
        1.jpg
        2.jpg
        3.jpg
        ...
```
Right？

**Comment by vbvg2008** [comment]
Hi, 

To use custom dataset in our YOLOv5 apphub, you just need to set up a proper `Dataset` access. The easiest way in my opinion is to create a csv file with the following headers: `image` and `bbox`. The `bbox` follows MSCOCO format - (x1, y1, width, height, label), with x1, y1 being the pixel coordinate of the top-left corner of bounding box. If there are multiple objects in one image, you can simply add multiple of those object sets like shown in row2.

| image | bbox |
| --- | ----------- |
| /path/to/your/image1.jpg | [(1, 5, 103, 23,  0)] |
| /path/to/your/image2.png | [(2, 6, 32, 28, 9), (8, 62, 103, 256, 5)] |



Then inside the code, you can use our built-in `CSVDataset` to read them. 

```python
from fastestimator.dataset import CSVDataset

train_ds = CSVDataset("csv_file.csv")

len(train_ds) # check how many samples are there. In the above csv file, we have 2 samples.
>>> 2

train_ds[0] # index the first sample
>>> {'image': '/path/to/your/image1.jpg', 'bbox': '[(1, 5, 103, 23,  0)]'}

train_ds[1] # index the second sample
>>> {'image': '/path/to/your/image2.jpg', 'bbox': '[(2, 6, 32, 28, 9), (8, 62, 103, 256, 5)]'}
```


Next, you can use this csv dataset and plug it in the existing yolov5 code.  But pay attention that  the `bbox` data type is currently a string rather than a list of tuples. Therefore we can use literal eval in `PreMosaicDataset` to convert them into list of tuples.

```python
class PreMosaicDataset(Dataset):
    def __init__(self, mscoco_ds):
        self.mscoco_ds = mscoco_ds

    def __len__(self):
        return len(self.mscoco_ds)

    def __getitem__(self, idx):
        indices = [idx] + [random.randint(0, len(self) - 1) for _ in range(3)]
        samples = [self.mscoco_ds[i] for i in indices]
        return {
            "image1": samples[0]["image"],
            "bbox1": eval(samples[0]["bbox"]),  # use literal eval
            "image2": samples[1]["image"],
            "bbox2": eval(samples[1]["bbox"]), # use literal eval
            "image3": samples[2]["image"],
            "bbox3": eval(samples[2]["bbox"]), # use literal eval
            "image4": samples[3]["image"],
            "bbox4": eval(samples[3]["bbox"]) # use literal eval
        }

# train_ds, val_ds = mscoco.load_data(root_dir=data_dir)
train_ds = CSVDataset("csv_file_train.csv")
train_ds = PreMosaicDataset(mscoco_ds=train_ds)
```
In the YOLOv5 example, we were using MSCOCO dataset specific metrics (mAP), you can comment the `MeanAveragePrecision ` out when using custom dataset.  The rest of the code should work fine.

If you encounter further issue, let me know.

**Comment by WangRongsheng** [comment]
thank you！
